Nested link fix
romansky/dom-to-semantic-markdown pull request #17
Opened 2024-09-16 22:34 UTC by rynomad

links inside <strong> weren't working, now they are.

e.g

```
<strong><a href="http://example.com">link me</a></strong> - was doing -> **link me**
                                                                                                          - now doing -> **[link me](http://example.com)**
```

added a test case too.

2024-09-16 22:36 UTC, rynomad commented
oops, accidentally cluttered git history with bundle, I reverted it but can do a cleaner PR if it's a big deal

2024-09-17 07:33 UTC, romansky requested changes
Great pull request! please fix the few issues and I'm happy to merge.

2024-09-17 07:33 UTC, romansky commented on src/core/markdownASTToString.ts
> -                        // Check if the link contains only text
please add these comments back

2024-09-17 07:33 UTC, romansky commented on src/core/markdownASTToString.ts
> -                            // Use native markdown syntax for text-only links
please add these comments back

2024-09-17 07:33 UTC, romansky commented on src/core/markdownASTToString.ts
> -                            // Use HTML <a> tag for links with rich content
please add these comments back

2024-09-17 07:33 UTC, romansky commented on src/core/markdownASTToString.ts
> +                        if (!isPrevNodeFormatting && markdownString.length > 0 && !/\s$/.test(markdownString)) {
/\s$/.test(markdownString) is an O(n) operation and could be quite expensive with large documents.. please use /\s/.test(markdownString.slice(-1)) instead.
Also, please use the value from the dup code above..

2024-09-17 07:33 UTC, romansky commented on src/core/markdownASTToString.ts
> +                        if (!isPrevNodeFormatting && !isNextNodePunctuation && !/^\s/.test(node.content) && markdownString.length > 0 && !/\s$/.test(markdownString)) {
/\s$/.test(markdownString) is an O(n) operation and could be quite expensive with large documents.. please use /\s/.test(markdownString.slice(-1) instead.
Also, please move it a bit up and give this a meaningful name

2024-09-17 07:33 UTC, romansky commented on src/core/markdownASTToString.ts
> +                        if (!isNextNodePunctuation && nextNode) {
Not sure this is needed.. the next node should add it's own space in the beginning if it's needed

2024-09-17 19:07 UTC, rynomad commented
roger, will clean it up this evening!

2024-09-21 09:14 UTC, romansky requested changes
Almost there :)

2024-09-21 09:14 UTC, romansky commented on src/core/markdownASTToString.ts
> +                        if (!isNextNodePunctuation && nextNode) {
Please explain why this is needed..

2024-09-22 06:43 UTC, rynomad commented
Yeah sorry about the delay, was trying to get it over the line while waiting for a batch job to finish but got sucked back into it before i could finish, and my brain is currently mush for at least another day or so. Will complete asap. Love this lib btw, got a ton of other ideas to pitch you on. Expect more PRs :)

2024-09-25 03:42 UTC, rynomad commented
update: haven't forgotten, just swamped... might not be able to sit down with this until the weekend. In the spirit of honesty, claude wrote the initial PR because I just needed the problem solved and I'm using esm.sh pointed at my forked repo to unblock my work. I suppose this makes a good little case study on llm codegen being "technically correct" without regard for the bigger picture.

2024-10-05 21:35 UTC, rynomad commented
closing in favor of [new pr](https://github.com/romansky/dom-to-semantic-markdown/pull/17)

2024-10-05 21:35 UTC, closed without merging